defaults:
  - label_processor: label_binarizer # binarizer for sleep_quality

dataset: BiHeartS
side: left
label_name: ${label_name}
device_map: "mps"
threshold: 5
segment_length: 600 # seconds
sampling_rate: 4 # Hz
