# defaults:
#   - label_processor: label_binarizer # binarizer for SleepQuality

dataset: HeartS
side: unknown
label_name: sleep_wake
device_map: "mps"
label_processor: ${label_processor}
threshold: 3
segment_length: 600 # seconds
sampling_rate: 4 # Hz
