# defaults:
# # binarizer for 'engagement', 
# # label_binarizer for 'activity', 
#   - label_processor: binarizer 

dataset: HHISS_control_dataset
side: left
label_name: ${label_name}
label_processor: ${label_processor}
device_map: ${device_map}
segment_length: ${segment_length} # seconds
sampling_rate: 4 # Hz
