# defaults:
#   - label_processor: binarizer

dataset: LAUREATE
side: Unknown
label_name: ${label_name}
device_map: ${device_map}
label_processor: ${label_processor}
segment_length: ${segment_length} # seconds
sampling_rate: 4 # Hz
