model: 
    _target_: xgboost.XGBClassifier
    device: cpu
    n_jobs: 8
    seed: ${seed}
param_grid:
  n_estimators: [50, 100, 1000, 2000]
  max_depth: [3, 5, 10, 20]
  learning_rate: [0.01, 0.1, 0.1, 0.2]
  # n_estimators: [null]
  # max_depth: [null]
  # learning_rate: [null]
