defaults:
  - mainconf
  - override model: logistic_regression
  - override feature_extractor: chronos_large
  - override validation_method: lopo
  - _self_

override dataset: bihearts
override side: left

hydra:
  run:
    dir: ./outputs/${dataset}/${side}_${hydra:runtime.choices.model}_${hydra:runtime.choices.feature_extractor}/${hydra:runtime.choices.validation_method}/${now:%Y-%m-%d}/${now:%H-%M-%S}
    
# hydra:
#   run:
#     dir: ./outputs/${dataset}/${side}_${hydra:runtime.choices.model}_${hydra:runtime.choices.feature_extractor}/${hydra:runtime.choices.validation_method}/${now:%Y-%m-%d}/${now:%H-%M-%S}