defaults:
  - mainconf
  - override model: logistic_regression
  - override feature_extractor: handcrafted
  - override validation_method: lopo
  - _self_

override dataset: bihearts
override side: left

