defaults:
  - _self_
  - model: logistic_regression
  - feature_extractor: handcrafted_baseline_small
  - validation_method: lopo
  - resampling: none
  # aggregator is the method used to aggregate the features across the channels. 
  # Some feature extractors can accept the null: it means that the features can be computed
  # across channels
  # FIXME: none/null does not work, and I don't know how to fix it. For the moment, I 
  # just wrote down "None" in the code
  - aggregator: none # accepted: mean_chan, mean_time or none
  - dataset: apsync
  - feature_scaling_method: standard_scaler
  - sample_scaling_method: min_max_scale
  - label_processor: none
  - trainable_feature_extractor: none

sampling_rate: ${dataset.sampling_rate}
seed: 666
label_name: none # e.g. sleep_quality for SleepQuality, or stress for Apsync

datamodule:
  _target_: edamame_downstream.data.EDAMAMEDataset
  path_to_data: ../datasets_cleaning/data_ready_multimodal.nosync/${dataset.dataset}/data_${dataset.side}_${dataset.segment_length}s_multimodal.npz
  validation_method: ${validation_method}
  label_name: ${label_name}
  signals: [ACC]
  feature_extractors:
    EDA: ${feature_extractor}
    BVP: ${feature_extractor}
    ACC: ${feature_extractor}
    TEMP: ${feature_extractor}
  label_processor: ${dataset.label_processor}
  feature_scaling_methods: 
    EDA: ${feature_scaling_method}
    BVP: ${feature_scaling_method}
    ACC: ${feature_scaling_method}
    TEMP: ${feature_scaling_method}
  signal_kwargs:
    EDA:
      channels: [0, 1, 2]
    BVP:
      channels: [0]
    ACC:
      channels: [0, 1, 2]
    TEMP:
      channels: [0]
  sample_scaling_methods: 
    EDA: ${sample_scaling_method}
    BVP: ${sample_scaling_method}
    ACC: ${sample_scaling_method}
    TEMP: ${sample_scaling_method}
  recompute_features: true
  debug: false # !!!!!!!!!!!! SET TO FALSE FOR PRODUCTION !!!!!!!!!!!!

engine:
  _target_: edamame_downstream.engine.Engine
  model: ${model}
  scoring: 
    _target_: sklearn.metrics.balanced_accuracy_score
    _partial_: true
  inner_cv_folds: 3
  resampling: ${resampling}
  trainable_feature_extractor: ${trainable_feature_extractor}
  subsample_train_set: false
  n_jobs: 2
  additional_metrics:
    - _target_: sklearn.metrics.accuracy_score
      _partial_: true
    - _target_: sklearn.metrics.balanced_accuracy_score
      _partial_: true
    - _target_: sklearn.metrics.matthews_corrcoef
      _partial_: true
    - _target_: sklearn.metrics.f1_score
      _partial_: true
      average: macro
    - _target_: sklearn.metrics.precision_score
      _partial_: true
      average: macro
    - _target_: sklearn.metrics.recall_score
      _partial_: true
      average: macro
    - _target_: sklearn.metrics.roc_auc_score
      _partial_: true
      average: macro
