defaults:
  - _self_
  - model: logistic_regression
  - feature_extractor: edamame_efficientnet-userpair
  - validation_method: lopo
  - resampling: none
  # aggregator is the method used to aggregate the features across the channels. 
  # Some feature extractors can accept the null: it means that the features can be computed
  # across channels
  # FIXME: none/null does not work, and I don't know how to fix it. For the moment, I 
  # just wrote down "None" in the code
  - aggregator: none # accepted: mean_chan, mean_time or none
  - dataset: apsync
  - feature_scaling_method: standard_scaler
  - sample_scaling_method: none
  - label_processor: none
  - trainable_feature_extractor: none

sampling_rate: ${dataset.sampling_rate}
seed: 666

datamodule:
  _target_: edamame_downstream.data.EDADataset
  path_to_data: ${oc.env:DATA_PATH,./data.nosync/${dataset.dataset}/data_${dataset.side}_${dataset.label_name}_${dataset.segment_length}s.npz}
  validation_method: ${validation_method}
  feature_extractor: ${feature_extractor}
  label_processor: ${dataset.label_processor}
  feature_scaling_method: ${feature_scaling_method}
  channels: [0, 1, 2] # 0 mixed, 1 phasic, 2 tonic
  sample_scaling_method: ${sample_scaling_method}
  recompute_features: false
  debug: false # !!!!!!!!!!!! SET TO FALSE FOR PRODUCTION !!!!!!!!!!!!

engine:
  _target_: edamame_downstream.engine.Engine
  model: ${model}
  scoring: 
    _target_: sklearn.metrics.balanced_accuracy_score
    _partial_: true
  inner_cv_folds: 3
  resampling: ${resampling}
  trainable_feature_extractor: ${trainable_feature_extractor}
  subsample_train_set: false
  n_jobs: 2
  additional_metrics:
    - _target_: sklearn.metrics.accuracy_score
      _partial_: true
    - _target_: sklearn.metrics.balanced_accuracy_score
      _partial_: true
    - _target_: sklearn.metrics.matthews_corrcoef
      _partial_: true
    - _target_: sklearn.metrics.f1_score
      _partial_: true
      average: macro
    - _target_: sklearn.metrics.precision_score
      _partial_: true
      average: macro
    - _target_: sklearn.metrics.recall_score
      _partial_: true
      average: macro
    - _target_: sklearn.metrics.roc_auc_score
      _partial_: true
      average: macro
