defaults:
  - default
  # - sweeps@_here_: basic
  - override dataset: hearts
  # - override label_processor: extreme_only
  - override label_processor: label_binarizer
  - _self_

label_name: sleep_wake # accepted: sleep_wake, SleepQuality
segment_length: 60
device_map: "mps"

# label_processor:
#   lower_threshold: 2
#   upper_threshold: 4