defaults:
  - default
  - sweeps@_here_: basic
  - override dataset: hearts
  - override label_processor: label_binarizer
  - _self_

label_name: sleep_wake # accepted: sleep_wake, SleepQuality
segment_length: 60
device_map: "cpu"

# label_processor:
#   threshold: 3 # TODO: check if correct