defaults:
  - _self_
  - default
  - sweeps@_here_: basic
  - override dataset: m2sleep
  - override label_processor: binarizer

label_name: Avg_SleepQuality_label # accepted: Avg_SleepQuality_label, PSQI
segment_length: 600
device_map: "cpu"

label_processor.threshold: 4 # TODO: check if correct

# TODO: test if this is working!
hydra:
  sweeper:
    grid_params:
      label_name: Avg_SleepQuality_label, PSQI