defaults:
  - _self_
  - model: logistic_regression
  - feature_extractor: moment_large
  - validation_method: lopo
  # aggregator is the method used to aggregate the features across the channels. 
  # Some feature extractors can accept the null: it means that the features can be computed
  # across channels
  - aggregator: none # accepted: concat, mean or null

seed: 1

datamodule:
  _target_: src.data.EDADataset
  path_to_data: ${oc.env:DATA_PATH,./data.nosync/usilaughs/data.npz}
  validation_method: ${validation_method}
  feature_extractor: ${feature_extractor}

engine:
  _target_: src.engine.Engine
  model: ${model}
  scoring: accuracy
  inner_cv_folds: 3