defaults:
  - _self_
  - model: logistic_regression
  - feature_extractor: handcrafted
  - validation_method: lopo
  - aggregator: none
  - resampling: group_undersampler
  - override hydra/sweeper: list
  
seed: 42

hydra:
  mode: MULTIRUN
  sweep:
    dir: "outputs_bihearts_left/multirun_${now:%Y-%m-%d}_${now:%H-%M-%S}"
  sweeper:
    grid_params: 
      seed: 42
      validation_method: lopo, tacv
    # standard grid search
    list_params:
      model: random_baseline, logistic_regression, logistic_regression, logistic_regression, logistic_regression, logistic_regression, logistic_regression, logistic_regression, logistic_regression, logistic_regression, logistic_regression, logistic_regression, logistic_regression, logistic_regression
      aggregator: none, none, none, concat, mean_chan, mean_time, none, concat, mean_chan, mean_time, none, concat, mean_chan, mean_time
      feature_extractor: handcrafted, handcrafted, chronos_large, chronos_large, chronos_large, chronos_large, moment_large, moment_large, moment_large, moment_large, chronos_small, chronos_small, chronos_small, chronos_small

datamodule:
  _target_: src.data.EDADataset
  path_to_data: ${oc.env:DATA_PATH,./data.nosync/bihearts/data_left.npz}
  validation_method: ${validation_method}
  feature_extractor: ${feature_extractor}

engine:
  _target_: src.engine.Engine
  model: ${model}
  scoring: accuracy
  inner_cv_folds: 3
  resampling: ${resampling}