defaults:
  - _self_
  - model: logistic_regression
  - feature_extractor: mantis
  # - feature_extractor: chronos_large
  - validation_method: tacv
  - resampling: none
  # aggregator is the method used to aggregate the features across the channels. 
  # Some feature extractors can accept the null: it means that the features can be computed
  # across channels
  # FIXME: none/null does not work, and I don't know how to fix it. For the moment, I 
  # just wrote down "None" in the code
  - aggregator: none # accepted: mean_chan, mean_time or none

seed: 1

dataset: usilaughs
side: right
device_map: "mps"

# hydra:
#   run:
#     dir: ./outputs/${dataset}/${side}_${hydra:runtime.choices.model}_${hydra:runtime.choices.feature_extractor}/${hydra:runtime.choices.validation_method}/${now:%Y-%m-%d}/${now:%H-%M-%S}

datamodule:
  _target_: src.data.EDADataset
  path_to_data: ${oc.env:DATA_PATH,./data.nosync/${dataset}/data_${side}.npz}
  validation_method: ${validation_method}
  feature_extractor: ${feature_extractor}

engine:
  _target_: src.engine.Engine
  model: ${model}
  scoring: 
    _target_: sklearn.metrics.balanced_accuracy_score
    _partial_: true
  inner_cv_folds: 3
  resampling: ${resampling}
  n_jobs: 3
  additional_metrics:
    - _target_: sklearn.metrics.accuracy_score
      _partial_: true
    - _target_: sklearn.metrics.balanced_accuracy_score
      _partial_: true
    - _target_: sklearn.metrics.matthews_corrcoef
      _partial_: true
    - _target_: sklearn.metrics.f1_score
      _partial_: true
      average: macro
    - _target_: sklearn.metrics.precision_score
      _partial_: true
      average: macro
    - _target_: sklearn.metrics.recall_score
      _partial_: true
      average: macro
    - _target_: sklearn.metrics.roc_auc_score
      _partial_: true
      average: macro
