# NOTE: DOES NOT WORK!!!
defaults:
  - default
  # - sweeps@_here_: basic-local
  - override dataset: multiphysio
  - override label_processor: custom_selector
  - _self_

label_name: event # accepted: cognitiveload
dataset.side: shimmer # accepted: shimmer, empatica -> used to identify the device here!
segment_length: 60 # in seconds
device_map: "mps" # accepted: "cpu", "cuda", "mps"
# FIXME: device_map is not working
# NOTE: edamame does not support mps. I need to fix it.

label_processor:
  positive_class: ["describe"]
  negative_class: ["baseline"]

datamodule:
  recompute_features: true
#   channels: [1, 2] # 0 mixed, 1 phasic, 2 tonic
#   sample_scaling_method: 
#     _target_: edamame.utils.sample_scaling.min_max_scaling
#     _partial_: true