defaults:
  - default
  # - sweeps@_here_: basic-local
  - override dataset: multiphysio_2
  - override label_processor: custom_selector
  - _self_

label_name: task # accepted: task
dataset.side: emotibit_dorsal # accepted: shimmer_wrist, shimmer_finger, emotibit_dorsal, emotibit_volar -> used to identify the device here!
segment_length: 60 # in seconds
device_map: "mps" # accepted: "cpu", "cuda", "mps"
# FIXME: device_map is not working
# NOTE: edamame does not support mps. I need to fix it.

# NOTE on fine-tune mantis: lr 7e-5, batch 8 and epoch 7

# "relax", "squat", "sit", "video1" and "video2"
label_processor:
  positive_class: ["video1", "video2"]
  negative_class: ["relax"]

datamodule:
  recompute_features: true
#   channels: [1, 2] # 0 mixed, 1 phasic, 2 tonic
#   sample_scaling_method: 
#     _target_: edamame.utils.sample_scaling.min_max_scaling
#     _partial_: true