defaults:
  - _self_
  - model: logistic_regression
  - feature_extractor: none
  - validation_method: tacv
  - aggregator: none
  - resampling: none
  - override hydra/sweeper: list
  
seed: 42
dataset: apsync
side: engagement_10sec_4thresh
device_map: "mps"

hydra:
  mode: MULTIRUN
  sweep:
    dir: "outputs/none_sweep/multirun_${now:%Y-%m-%d}-${now:%H-%M-%S}"
    # FIXME: when using runtime.choices with a string, it returns "None"
    # subdir: "${hydra:runtime.choices}-${hydra:runtime.choices.validation_method}"
  sweeper:
    grid_params: 
      seed: 42
      validation_method: lopo, tacv
    # standard grid search
    list_params:
      # dataset: apsync, seed, usilaughs, bihearts
      # side: engagement_10sec_4thresh, engagement_10sec_35thresh, right, left
      # resampling: none, none, none, group_undersampler
      dataset: apsync, apsync, apsync, apsync
      side: enjoyment_10sec, immersion_10sec, engagement_10sec_35thresh, engagement_10sec_medianthresh
      resampling: none, none, none, none


datamodule:
  _target_: src.data.EDADataset
  path_to_data: ${oc.env:DATA_PATH,./data.nosync/${dataset}/data_${side}.npz}
  validation_method: ${validation_method}
  feature_extractor: ${feature_extractor}
  debug: false # !!!!!!!!!!!! SET TO FALSE FOR PRODUCTION !!!!!!!!!!!!

engine:
  _target_: src.engine.Engine
  model: ${model}
  scoring: 
    _target_: sklearn.metrics.balanced_accuracy_score
    _partial_: true
  inner_cv_folds: 3
  resampling: ${resampling}
  n_jobs: 3
  additional_metrics:
    - _target_: sklearn.metrics.accuracy_score
      _partial_: true
    - _target_: sklearn.metrics.balanced_accuracy_score
      _partial_: true
    - _target_: sklearn.metrics.matthews_corrcoef
      _partial_: true
    - _target_: sklearn.metrics.f1_score
      _partial_: true
      average: macro
    - _target_: sklearn.metrics.precision_score
      _partial_: true
      average: macro
    - _target_: sklearn.metrics.recall_score
      _partial_: true
      average: macro
    - _target_: sklearn.metrics.roc_auc_score
      _partial_: true
      average: macro
