defaults:
  - default
  - sweeps@_here_: basic
  - override dataset: seed2lab
  - override label_processor: binarizer
  - _self_

label_name: Anxious # TODO accepted:
segment_length: 10 # in seconds
device_map: "cpu" # accepted: "cpu", "cuda", "mps"

label_processor:
  threshold: 4