defaults:
  - mainconf
  - override model: logistic_regression
  - override feature_extractor: handcrafted
  - override validation_method: tacv
  - _self_

dataset: usilaughs
side: right

hydra:
  run:
    dir: ./outputs/${dataset}/${side}_${hydra:runtime.choices.model}_${hydra:runtime.choices.feature_extractor}/${hydra:runtime.choices.validation_method}/${now:%Y-%m-%d}/${now:%H-%M-%S}