defaults:
  - default
  - sweeps@_here_: basic
  - override dataset: workplace
  - override label_processor: none
  - _self_

# NOTE: we define the variable as global, instad of calling `dataset.var`, in order not
# to have default values in the dataset config file.
label_name: engagement # TODO: accepted: engagement, enjoyment, motivation, performance
segment_length: 10 # in seconds
device_map: "cpu" # accepted: "cpu", "cuda", "mps"

# TODO: test if this is working!
hydra:
  sweeper:
    grid_params:
      label_name: engagement, enjoyment, motivation, performance