defaults:
  - _self_
  - override /hydra/sweeper: list

hydra:
  mode: MULTIRUN
  sweep:
    dir: "outputs/${dataset.dataset}-${dataset.side}/multirun_${now:%Y-%m-%d}-${now:%H-%M-%S}"
    # subdir: "${hydra:runtime.choices.model}-${hydra:runtime.choices.feature_extractor}-${hydra:runtime.choices.aggregator}-${hydra:runtime.choices.validation_method}-${label_name}-${seed}-${datamodule.channels}-${sample_scaling_method}"
  sweeper:
    grid_params: 
      seed: 42, 56, 324, 123, 987
      validation_method: lnpo
      datamodule.channels: 
      # - [0]
      - [1]
      - [2]
      # - [0, 1, 2]
      # - [1, 2]
      sample_scaling_method:
        - none
        # - min_max_scale
        # - min_max_scale_per_user
        # - z_score
    list_params:
      model: 
      # - random_baseline
      # - logistic_regression
      # - xgboost
      # - logistic_regression
      - logistic_regression
      aggregator: 
      # - none
      # - none
      # - none
      - mean_chan
      # - none
      feature_extractor: 
      # - handcrafted
      # - handcrafted
      # - handcrafted
      - edamame_efficientnet
      # - mantis