defaults:
  - _self_
  - override /hydra/sweeper: list

hydra:
  mode: MULTIRUN
  # mode: RUN
  sweep:
    dir: "outputs/${dataset.dataset}-${dataset.side}/multirun_${now:%Y-%m-%d}-${now:%H-%M-%S}"
    # subdir: "${hydra:runtime.choices.model}-${hydra:runtime.choices.feature_extractor}-${hydra:runtime.choices.aggregator}-${hydra:runtime.choices.validation_method}-${label_name}-${seed}-${datamodule.channels}-${sample_scaling_method}"
  sweeper:
    grid_params: 
      seed: 42
      validation_method: tacv
      datamodule.channels: 
      # - [0]
      # - [1]
      # - [2]
      - [0, 1, 2]
      # - [1, 2]
      sample_scaling_method:
        - none
        # - min_max_scale
        # - min_max_scale_per_user
        # - z_score
    list_params:
      model: 
      # - random_baseline
      - logistic_regression
      - svm
      - xgboost
      # - logistic_regression
      # # - logistic_regression
      # - logistic_regression
      # - logistic_regression
      # - logistic_regression
      aggregator: 
      # - none
      # - none
      # - none
      # # - none
      # - none
      # - none
      - mean_time
      feature_extractor: 
      # - handcrafted_baseline_small
      # - handcrafted_baseline_small
      # - handcrafted_baseline_small
      # # - edamame_efficientnet
      # # - edamame_efficientnet_random
      # - mantis
      # - moment_large
      - chronos_small